### ISSUE TITLE
Update vulnerable dependencies

### ISSUE THREAD

**Issue by xoxys** [owncloud/kimai-dashboard#2]
See https://github.com/owncloud/kimai-dashboard/network/alerts.

@JannikZed could you update the dependencies? @felixboehm \cc

**Comment by JannikZed** [comment]
I can't access the link you posted - getting just a 404.

I updated the dependencies and created a pull request. We have no master-branch rights, so I can't merge it myself.

**Comment by xoxys** [comment]
Ah ok so here is the screenshot:
![grafik](https://user-images.githubusercontent.com/3391958/84020042-7317be80-a982-11ea-981d-e69ea33d6d6e.png)

I'll review the PR and merge it, thanks :)

**Comment by xoxys** [comment]
Thanks, solved for now.
