### ISSUE TITLE
Planning to be released on the marketplace

### ISSUE THREAD

**Issue by mmattel** [owncloud/kimai-dashboard#8]
@xoxys are you planning to release this app on the marketplace?

If this is the intention, can you tell an ETA and if there is something to do be documented in the docs repro and/or here in readme ?

**Comment by xoxys** [comment]
Not sure if I understand you right, but this is a custom Nodejs app for Kimai and no oC app. So, no we don't plan to publish this on the ownCloud marketplace.

**Comment by mmattel** [comment]
Thanks for clarification. Maybe you put that comment in readme to make it available to other readers.

**Comment by xoxys** [comment]
Done.
